[package]
name = "aoc-2021"
version = "0.1.0"
authors = ["JustinRlle <justinrlle@pm.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-runner = { git = "https://github.com/justinrlle/aoc-runner"}
